const MlData = [
    {
        mlId: 1,
        mlDate: '01/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 2,
        mlDate: '02/11/2023',
        mlCod: 64.4,
        mlPb: 0.32,
        mlCu: 'ND',
        mlMn: 0.8,
        mlZn: 0.16,
        mlBoron: 2.84,
        mlIron: 0.68,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 3,
        mlDate: '03/11/2023',
        mlCod: 86.4,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.08,
        mlBoron: 2.32,
        mlIron: 1.44,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 4,
        mlDate: '04/11/2023',
        mlCod: 80.4,
        mlPb: 0.04,
        mlCu: 'ND',
        mlMn: 0.4,
        mlZn: 0.12,
        mlBoron: 6.08,
        mlIron: 0.84,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 5,
        mlDate: '05/11/2023',
        mlCod: 74.0,
        mlPb: 0.04,
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.24,
        mlBoron: 5.28,
        mlIron: 0.12,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 6,
        mlDate: '06/11/2023',
        mlCod: 94.0,
        mlPb: 0.04,
        mlCu: 0.04,
        mlMn: 0.4,
        mlZn: 0.32,
        mlBoron: 3.56,
        mlIron: 0.64,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 7,
        mlDate: '07/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 8,
        mlDate: '08/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 9,
        mlDate: '09/11/2023',
        mlCod: 93.2,
        mlPb: 0.2,
        mlCu: 'ND',
        mlMn: 0.4,
        mlZn: 0.08,
        mlBoron: 2.16,
        mlIron: 0.04,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 10,
        mlDate: '10/11/2023',
        mlCod: 67.2,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.04,
        mlBoron: 3.12,
        mlIron: 0.36,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 11,
        mlDate: '11/11/2023',
        mlCod: 67.2,
        mlPb: 0.08,
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.2,
        mlBoron: 4.08,
        mlIron: 1.08,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 12,
        mlDate: '12/11/2023',
        mlCod: 74.0,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.4,
        mlBoron: 3.64,
        mlIron: 0.76,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 13,
        mlDate: '13/11/2023',
        mlCod: '',
        mlPb: 0.04,
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.28,
        mlBoron: 2.84,
        mlIron: 0.24,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 14,
        mlDate: '14/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 15,
        mlDate: '15/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 16,
        mlDate: '16/11/2023',
        mlCod: 83.6,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.28,
        mlBoron: 3.4,
        mlIron: 0.36,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 17,
        mlDate: '17/11/2023',
        mlCod: 73.2,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.32,
        mlBoron: 1.32,
        mlIron: 1.04,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 18,
        mlDate: '18/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 19,
        mlDate: '19/11/2023',
        mlCod: '',
        mlPb: '',
        mlCu: '',
        mlMn: '',
        mlZn: '',
        mlBoron: 0,
        mlIron: '',
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 20,
        mlDate: '20/11/2023',
        mlCod: 93.2,
        mlPb: 0.2,
        mlCu: 'ND',
        mlMn: 0.4,
        mlZn: 0.08,
        mlBoron: 2.16,
        mlIron: 0.04,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 21,
        mlDate: '21/11/2023',
        mlCod: 74.0,
        mlPb: 'ND',
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.4,
        mlBoron: 3.64,
        mlIron: 0.76,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    },
    {
        mlId: 22,
        mlDate: '22/11/2023',
        mlCod: 74.0,
        mlPb: 0.04,
        mlCu: 'ND',
        mlMn: 'ND',
        mlZn: 0.24,
        mlBoron: 5.28,
        mlIron: 0.12,
        mlDateTime: '',
        mlEnviLab: '',
        mlTime: '15:00',
        mlUser: ''
    }
];

export default MlData;